# Generated by Django 3.2.5 on 2021-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
