# Generated by Django 3.2.5 on 2021-07-20 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrAttendanceSheet', '0002_auto_20210717_2059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_presence',
            unique_together={('course_session', 'student')},
        ),
    ]
