# Generated by Django 3.2.5 on 2021-07-20 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qrAttendanceSheet', '0003_alter_student_presence_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_presence',
            name='entrance_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
